[build]
  functions = 'functions' # must specify a functions folder for this to work
[[plugins]]
  package = 'netlify-plugin-search-index'
  [plugins.inputs]
    generatedFunctionName = 'null'
    publishDirJSONFileName = './search/searchIndex' # you can use / to nest in a directory
    exclude = ['/404.html', '''\/page\/''']